### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by jrgnicho** [moveit/moveit_kinematics_tests#1]
@davetcoleman I just finished creating a jade-devel branch which is a slight departure from the original repo that lives under my account.  The few changes I made eliminate the dependencies from the kuka and motoman repos; which mainly provided urdf and mesh resources for the unit tests.  I also updated the install.rosinstall file , however I don't know if this file should be kept at all given that it is not consider a part of the automated jenkins build process as far as I know.  Please advice

**Comment by davetcoleman** [comment]
I think it makes sense to keep it, might be useful in the future.

Also, could we get a jenkins automated build process? I guess if we released this as a full ROS debian, we could leverage the pre-existing ROS/bloom infrastructure for our tests. But that seems like a hacky solution, MoveIt! rather needs an independent continuous integration to replace travis (since travis hasn't been upgraded to 14.04 last time I checked). Thoughts? 

Finally: I created a cloned indigo-devel branch, and I deleted the master branch.

**Comment by sachinchitta** [comment]
Why is the ROS/bloom infrastructure a hacky solution - just curious.

**Comment by tfoote** [comment]
@davetcoleman FYI you can run the new style ROS devel jobs relatively easily on your own hardware https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst#run-the-devel-job-locally

Also once we drop hydro from the ROS buildfarm we'll be able to support turning on PR builds on the ros jenkins instance.

**Comment by davetcoleman** [comment]
@sachinchitta I had originally meant we could release a debian that includes the kinematics tests, so that it would alert of us build or runtime errors. I thought it was a hacky solution because I believe bloom is intended to distribute software, not do continuous integration.

@tfoote that's great news re:PR builds. something i think moveit really needs
